name: HelloWorld
version: '${project.version}'
main: com.bluedev.helloworld.HelloWorld
api-version: '1.18'
commands:
  helloworld:
    description: Hello World Command
    aliases: hw, hello, world, helloworld, 헬로, 안녕, 안녕세계